program: growth_recursive.py
project: TVC_examples
name: train_loss_growth_recursive_g0_far_from_steady_state
description: HPO for train_loss growth recursive sequential g=0 with grid far from the steady state
method: bayes
metric:
  # See the  asset_pricing_sequential.py log_and_save
  name: hpo_objective 
  goal: minimize

parameters:
  # Fix parameters here:
  trainer.logger.offline:
    value: false # log online for W&B optimization
  trainer.max_time:
    value: 00:00:02:00  # these tests shouldn't take more than 2 minutes
  model.hpo_objective_name:
    value: train_loss
  model.always_log_hpo_objective:
    value: true
   # Stopping criteria
  trainer.callbacks.monitor:
    value: train_loss
  trainer.callbacks.stopping_threshold:
    value: 1.0e-8

# Provide distributions and variations for optimizer
  optimizer.lr:
    min: 0.01
    max: 1.0
  
  model.k_grid_min: 
    value: 0.8
  model.k_grid_max: 
    value: 1.5
  model.z_grid_min: 
    value: 1.0
  model.z_grid_max: 
    value: 1.0
  model.k_sim_grid_points: 
    value: 16
  model.z_sim_grid_points: 
    value: 1
  model.max_T_test:
    value: 20
    