program: asset_pricing_sequential.py
project: TVC_examples
name: train_loss_asset_seq_g_positive_linear_scaling
description: HPO for train_loss asset pricing sequential g = 0.02  c = 0 with linear scaling
method: bayes
metric:
  # See the  asset_pricing_sequential.py log_and_save
  name: hpo_objective 
  goal: minimize

parameters:
  # Fix parameters here:
  trainer.logger.offline:
    value: false # log online for W&B optimization
  trainer.max_time:
    value: 00:00:02:00  # these tests shouldn't take more than 2 minutes
  model.hpo_objective_name:
    value: train_loss
  model.always_log_hpo_objective:
    value: true
   # Stopping criteria
  trainer.callbacks.monitor:
    value: train_loss
  trainer.callbacks.stopping_threshold:
    value: 1.0e-7

# Provide distributions and variations for optimizer
  optimizer.lr:
    min: 0.01
    max: 1.0
# Economic model parameters 
  model.g:
    value: 0.02
  model.c:
    value: 0.0
# Using the neural net with the linear scaling layer
  model.ml_model.class_path:
    value:  econ_layers.layers.FlexibleSequential
  model.ml_model.init_args.n_in:
    value: 1
  model.ml_model.init_args.n_out:
    value: 1
  model.ml_model.init_args.layers:
    value: 4
  model.ml_model.init_args.hidden_dim: 
    value: 128
  model.ml_model.init_args.hidden_bias: 
    value: true
  model.ml_model.init_args.last_bias: 
    value: true
  model.ml_model.init_args.activator.class_path:
    value: torch.nn.Tanh
  model.ml_model.init_args.last_activator.class_path:
    value: torch.nn.Softplus
  model.ml_model.init_args.OutputRescalingLayer.class_path:
    value: econ_layers.layers.RescaleOutputsByInput
  model.ml_model.init_args.OutputRescalingLayer.init_args.bias:
    value: true