
#asset pricing 

python generate_figures/asset_pricing_sequential_g_histogram.py
python generate_figures/asset_pricing_sequential_g_positive_ensemble.py
python generate_figures/asset_pricing_sequential_g_positive_linear_scaling_ensemble.py
python generate_figures/asset_pricing_sequential_g0_grids.py
python generate_figures/asset_pricing_sequential_g0_t_max_9_ensemble.py
python generate_figures/asset_pricing_sequential_g0_t_max_14_ensemble.py
python generate_figures/asset_pricing_sequential_g0.py
python generate_figures/asset_pricing_sequential_g0_one_run.py

# growth sequential

python generate_figures/growth_sequential_g_positive_ensemble.py
python generate_figures/growth_sequential_g_positive_linear_rescaling_ensemble.py
python generate_figures/growth_sequential_g0_grids.py
python generate_figures/growth_sequential_g0_one_run.py
python generate_figures/growth_sequential_g0.py
python generate_figures/growth_sequential_g0_t_max_4_ensemble.py
python generate_figures/growth_sequential_g0_t_max_9_ensemble.py
python generate_figures/growth_sequential_small_k0.py
python generate_figures/growth_sequential_violating_tvc_paths_above.py
python generate_figures/growth_sequential_violating_tvc_paths_below.py
python generate_figures/growth_sequential_multiple_steady_states_four_initial_k_0.py
python generate_figures/growth_sequential_multiple_steady_states_var_initial_k_0_full.py
python generate_figures/growth_sequential_multiple_steady_states_var_initial_k_0.py
python generate_figures/growth_sequential_g0_sparse_grids.py


# growth recursive

python generate_figures/growth_recursive_analytic_solutions.py
python generate_figures/growth_recursive_g_positive_ensemble.py
python generate_figures/growth_recursive_g_positive_var_initial_k_0_one_run.py
python generate_figures/growth_recursive_g0_ensemble.py
python generate_figures/growth_recursive_g0_euler_residuals_grid_reg.py
python generate_figures/growth_recursive_g0_euler_residuals_grid.py
python generate_figures/growth_recursive_g0_far_from_steady_state_ensemble.py
python generate_figures/growth_recursive_g0_var_initial_k_0_one_run.py
python generate_figures/growth_recursive_g0_multiple_steady_states_capital_consumption_ensemble.py
python generate_figures/growth_recursive_g0_multiple_steady_states_capital_rel_error_ensemble.py
python generate_figures/growth_recursive_g0_multiple_steady_states_consumption_rel_error_ensemble.py

